name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # إعداد نسخة جافا المتوافقة مع أندرويد الحديث
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x' # تثبيت إصدار مستقر يتوافق مع حزمك
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # أمر لضمان ترقية ملفات الأندرويد سحابياً لتدعم SDK 34 تلقائياً
      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
